#!perl
use v5.34.0;
use warnings;

use Cpanel::JSON::XS;
use LWP::UserAgent;

my $url = q{https://api.linear.app/graphql};
my $lwp = LWP::UserAgent->new;
$lwp->default_header(Authorization => "...");

my $JSON = Cpanel::JSON::XS->new->pretty->canonical;

sub query {
  my ($query) = @_;

  my $res = $lwp->post(
    $url,
    'Content-Type' => 'application/json',
    Content => encode_json({ query => $query }),
  );

  die $res->as_string unless $res->is_success;

  decode_json($res->content);
}

say $JSON->encode(
  query(q[
  query Me {
    viewer {
      id
      name
      email
    }
  }
  ])
);

my $issues = query(q[
query Issues {
  issues(filter: {
    assignee: { email: { eq: "rjbs@fastmailteam.com" } }
    state:    { name:  { nin: [ "Done", "Canceled" ] } }
  }) {
    nodes {
      id
      identifier
      title
      state { name }
      team { id name }
    }
  }
}
]);

say $JSON->encode($issues);

my $create = query(q[
mutation CreateIssue {
  issueCreate(
    input: {
      title: "Created via Lin GraphQL Miranda",
      description: "This item will be destroyed.",
      teamId: "c4196244-4381-498b-ae0b-9288fc459cdd",
    }
  ) {
    success
    issue { identifier }
  }
}
]);

say $JSON->encode($create);
