#!perl
use v5.24.0;
use warnings;

use experimental 'signatures';

use Future::AsyncAwait;

use lib 'lib';

use Linear::Client;

binmode STDOUT, ":utf8";

my $auth = $ENV{LINEAR_AUTH} // die "no LINEAR_AUTH env var set!\n";

my $client = Linear::Client->new({
  auth_token => $auth,
});

async sub do_list {
  my $user = await $client->get_authenticated_user;
  my $query_result = await $client->search_issues({
    assignee => $user->{id},
    closed   => 0,
  });

  while ($query_result) {
    for my $node ($query_result->payload->{nodes}->@*) {
      printf "%10s - %s%s\n",
        $node->{identifier},
        ($node->{priority} == 1 ? "\N{FIRE} " : ""),
        $node->{title};
    }

    say "---" if $query_result->has_next_page;

    $query_result = await $query_result->next_page;
  }

  return;
}

await do_list;
