#!perl
use v5.24.0;
use warnings;

use experimental 'signatures';

use Future::AsyncAwait;

use lib 'lib';

use Linear::Client;

binmode STDOUT, ":utf8";

my $auth = $ENV{LINEAR_AUTH} // die "no LINEAR_AUTH env var set!\n";

my $client = Linear::Client->new({
  auth_token => $auth,
});

async sub do_list {
  my $user = await $client->get_authenticated_user;
  my $query_result = await $client->search_issues({
    assignee => $user->{id},
  });

  for my $node ($query_result->{data}{issues}{nodes}->@*) {
    printf "%10s - %s%s\n",
      $node->{identifier},
      ($node->{priority} == 1 ? "\N{FIRE} " : ""),
      $node->{title};
  }

  return;
}

await do_list;
